---
- name: Install packages
  become: yes
  yum:
    name: "{{item}}"
    state: latest
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker CE repo
  become: yes
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  become: yes
  yum:
    name: docker
    state: latest

- name: Update dockerd to bind to all addresses
  become: yes
  lineinfile:
    dest: /lib/systemd/system/docker.service
    line: "ExecStart=/usr/bin/dockerd-current -H=tcp://0.0.0.0:4243 \\"
    regexp: "^ExecStart=/usr/bin/dockerd-current "
  notify:
    - reload systemd
    - restart docker

- name: Start and enable the Docker daemon
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
