---
- name: Set hostname as per the inventory file
  become: yes
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Update hosts file to know the new hostname
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1    {{ inventory_hostname }}"
    regexp: "^127.0.0.1    {{ inventory_hostname }}$"
