---
- name: Update packages on Centos host
  become: True
  yum:
    name: "*"
    state: latest
  when: ansible_distribution == "CentOS"

- name: Update packages on Raspberry host
  become: True
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_distribution == "Debian"
