---
- name: Update packages on Centos host
  become: yes
  yum:
    name: "*"
    state: latest
  when: ansible_distribution == "Centos"

- name: Update packages on Raspberry host
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_distribution == "Debian"
