---
- name: Intall packages
  tags: packages
  become: yes
  yum:
    name: "{{item}}"
    state: latest
  loop:
    - vim
    - tmux

- name: Make sure firewall is NOT running
  tags: firewall
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_distribution == "Centos"
