---
- name: Download rust install and install
  connection: local
  block:
    - name: Check if cargo is installed
      tags: rust
      ansible.builtin.shell: which cargo
      register: cargo_output
      changed_when: false
      ignore_errors: true

    - name: Download rust installer
      when: cargo_output is failed
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: true

    - name: Install rust from the installer
      when: cargo_output is failed
      ansible.builtin.shell: /tmp/sh.rustup.rs -y
