---

- name: Add my user to the workstation
  tags: add_user
  ansible.builtin.import_tasks: ubuntu/add_user.yml

- name: Setup the Wifi
  tags: wifi
  ansible.builtin.import_tasks: ubuntu/wifi.yml

# - name: Install ansible galaxy collections
#   community.general.ansible_galaxy_install:
#     type: collection
#     name:

- name: Dotfiles
  tags: dotfiles
  ansible.builtin.import_tasks: ubuntu/dotfiles.yaml

- name: Browser
  tags: browser
  ansible.builtin.import_tasks: ubuntu/browser.yaml

- name: Rust
  tags: Rust
  ansible.builtin.import_tasks: ubuntu/rust.yaml

- name: Prusaslicer
  tags: prusaslicer
  ansible.builtin.import_tasks: ubuntu/prusa.yaml

- name: Calibre
  tags: calibre
  ansible.builtin.import_tasks: ubuntu/calibre.yaml

- name: Signal
  tags: signal
  ansible.builtin.import_tasks: ubuntu/signal.yaml

- name: Install packages
  become: true
  connection: local
  tags: packages
  ansible.builtin.package:
    name: "{{ item }}"
  loop: "{{ workstation_ubuntu_apt_applications }}"

- name: Remove packages
  become: true
  connection: local
  tags: packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ workstation_ubuntu_apt_remove_applications }}"

- name: Install stuff from pipx
  connection: local
  tags: packages
  community.general.pipx:
    name: "{{ item }}"
  loop: "{{ workstation_ubuntu_pipx_applications }}"

- name: Install stuff from snap
  connection: local
  become: true
  community.general.snap:
    name: "{{ workstation_ubuntu_snap_applications }}"

- name: Setup Brave browser setting
  connection: local
  block:
    - name: Make sure we have the policy directory
      become: true
      ansible.builtin.file:
        path: "{{ workstation_brave_browser_policy_directory }}"
        state: directory
        mode: "0755"

    - name: Copy configs for Brave policy
      become: true
      ansible.builtin.copy:
        content: "{{ workstation_brave_browser_policy_configs | to_nice_json }}"
        dest: "{{ workstation_brave_browser_policy_directory }}/{{ workstation_user_name }}.json"
        mode: "0755"

- name: Install some crates that are cool
  ansible.builtin.command: "cargo install {{ item }} --locked"
  loop: "{{ workstation_rust_crates }}"

- name: Dconf settings
  connection: local
  tags: dconf
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ workstation_dconf_settings }}"
