---
version: '2'

services:
  reverseproxy:
    image: reverseproxy
    ports:
      - 8080:8080
      - 8081:8081
    restart: always

  nginx:
    depends_on:
      - reverseproxy
    image: nginx:latest
    restart: always

  apache:
    depends_on:
      - reverseproxy
    image: httpd:latest
    restart: always
