[workspace]

members = [
    "variables",
    "hello-rust",
    "guessing_game",
    "functions",
    "enum_example",
    "structs",
    "control_flow",
    "loops",
    "errors",
    "strings",
    "collections",
    "traits",
]