---
workstation_user_name: "ramon"
workstation_user_comment: "Ramon Gonzalez"

workstation_ssh_pub_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA2dy1i+6iNAdFcPVNOG75KVMAM6J87Gnux1jtHJgFAFdbg3tySyWlWcXwwTHV7RRWOGhSpwY5Llqj5E29db2pG1RQ+Xb794ShN+3z+egMkAEbeX1wqG6WkkT35Wn8FJLLrbp6Bkv9QkJnsB87hJCfnmp9KNv5aj3eLlFx6W8y6vbn2JlE00AUnZbSvXOqo5bWDDWwESzw9u49VIm4EyqT1P5oJQBT/Ia/RDfhop5u4zuBxsRLo1W8KE/l7QtuazQWuVT+unj239t9be+HkIsBTTgdikIgnane6s7zd+4GKCYIdORDSptRzpkiLfBPGii0MpQ8QCm+AHAVguOEWqhM+w=="
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJQiFIgndiGT4087+9mHoUTJdlNoBJTzf1OGz6rjkIH1 rjgonza@gmail.com"

workstation_brave_browser_policy_directory: "/etc/brave/policies/managed"
workstation_brave_browser_policy_configs: "" # key/value pairs should be entered into this dict

workstation_dconf_settings:
  - key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"
  - key: "/org/gnome/shell/ubuntu/color-scheme"
    value: "'prefer-dark'"
  - key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"
  - key: "/org/gnome/shell/extensions/dash-to-dock/multi-monitor"
    value: "false"
  - key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"
  - key: "/org/gnome/desktop/interface/clock-show-seconds"
    value: "true"
  - key: "/org/gnome/shell/enabled-extensions"
    value: "['extension-list@tu.berry', 'ubuntu-dock@ubuntu.com', 'openweather-extension@jenslody.de', 'caffeine@patapon.info']"
  - key: "/org/gnome/shell/extensions/openweather/unit"
    value: "'fahrenheit'"
  - key: "/org/gnome/shell/extensions/openweather/wind-speed-unit"
    value: "'mph'"
  - key: "/org/gnome/shell/extensions/openweather/city"
    value: "'40.86403616103896,-74.07195789285714>Hasbrouck Heights, Bergen County, 07604, New Jersey, United States>0'"
  - key: "/org/gnome/shell/extensions/openweather/show-comment-in-panel"
    value: "true"

workstation_ubuntu_apt_applications:
  - build-essential # needed for rust
  - brave-browser
  - chrome-gnome-shell
  - cmake
  - dconf-editor
  - flatpak
  # - fuse # needed for appImages - aot says it's not need anymore
  # - gnome-browser-connector # Does not seem to work in 22.04
  - gnome-control-center
  - gnome-tweaks
  - libxcb-cursor0 # needed for Calibre
  - linssid
  - make # needed run the stow commands
  - netcat
  - pipx
  - signal-desktop
  - stow
  - tmux
  - vim
  - vlc

workstation_ubuntu_apt_remove_applications:
  - wallch

workstation_ubuntu_pipx_applications:
  - ansible
  - ansible-lint

workstation_ubuntu_snap_applications:
  - authy
  - bitwarden

workstation_prusaSlicer_url: "https://cdn.prusa3d.com/downloads/drivers/prusa3d_linux_2_7_1.zip"
workstation_prusaSlicer_directory: "/opt/prusaSlicer/"

workstation_wireless_interface: "wlp170s0"
workstation_wireless_network_ssid: "Gonzalez Expo Base"
# workstation_wireless_network_password: ""

workstation_rust_crates:
  - starship
